var t = new String("abcdkjfklajklfAFDAffdaf");
console.log(t.charAt(1));
.charCodeAt();
.concat();
.slice();
.toLowerCase();
.toUpperCase();
.replace();
.trim();
.substring();
.substr();
String.fromCharCode();